### ISSUE TITLE
Inference and Tracking Code

### ISSUE THREAD

**Issue by ruhyadi** [ruhyadi/yolo3d-lightning-archive#10]
Adding inference and tracking functions:

- [x] Inference Code
- [ ] Tracking with SORT
- [x] Utils to post assets to github release
- [x] Utils to get assets from github release
- [x] Utils to convert inference frames to video
- [x] Utils to convert inference video to gif
